export const blockchainActionTypes = {
    SET_HASH: "SET_HASH",
    SET_BLOCK: "SET_BLOCK",
    SET_BLOCKCHAIN: "SET_BLOCKCHAIN",
    SET_DISTRIBUTED: "SET_DISTRIBUTED",
    SET_TOKENS: "SET_TOKENS",
    SET_COINBASE: "SET_COINBASE",
    SET_FULL_BLOCKCHAIN: "SET_FULL_BLOCKCHAIN"
};

export const keysActionTypes = {
    SET_MESSAGE_SIGNATURE: "SET_MESSAGE_SIGNATURE",
    SET_TRANSACTIONS_SIGNATURE: "SET_TRANSACTIONS_SIGNATURE"
}